
# This function will load all 40 packages to their correct Trucks. The order in which they are loaded
# does not matter. However, loading packages to different trucks will lead to different total milage.
def organize(truck1, truck2, truck3, database):
    # Truck leaving right away at 8:00am
    truck1.loadPackage(database.search(14))
    truck1.loadPackage(database.search(15))
    truck1.loadPackage(database.search(19))
    truck1.loadPackage(database.search(1))
    truck1.loadPackage(database.search(13))
    truck1.loadPackage(database.search(16))
    truck1.loadPackage(database.search(20))
    truck1.loadPackage(database.search(29))
    truck1.loadPackage(database.search(30))
    truck1.loadPackage(database.search(34))
    truck1.loadPackage(database.search(40))
    truck1.loadPackage(database.search(2))
    truck1.loadPackage(database.search(4))
    truck1.loadPackage(database.search(5))
    truck1.loadPackage(database.search(7))
    truck1.loadPackage(database.search(8))
    # must leave at 9:05 to allow for delayed packages to arrive
    truck2.loadPackage(database.search(6))
    truck2.loadPackage(database.search(18))
    truck2.loadPackage(database.search(25))
    truck2.loadPackage(database.search(28))
    truck2.loadPackage(database.search(31))
    truck2.loadPackage(database.search(32))
    truck2.loadPackage(database.search(36))
    truck2.loadPackage(database.search(37))
    truck2.loadPackage(database.search(38))
    truck2.loadPackage(database.search(3))
    truck2.loadPackage(database.search(10))
    truck2.loadPackage(database.search(11))
    truck2.loadPackage(database.search(12))
    truck2.loadPackage(database.search(17))
    truck2.loadPackage(database.search(21))
    truck2.loadPackage(database.search(22))
    #Last truck to go out at 10:20am to allow for package #9 to correct it's address
    truck3.loadPackage(database.search(9)) # This is the corrected address, because it is now 10:20am
    truck3.loadPackage(database.search(23))
    truck3.loadPackage(database.search(24))
    truck3.loadPackage(database.search(26))
    truck3.loadPackage(database.search(27))
    truck3.loadPackage(database.search(33))
    truck3.loadPackage(database.search(35))
    truck3.loadPackage(database.search(39))